//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainTest.ServiceReferenceDMP {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceDMP.WebService2019Soap")]
    public interface WebService2019Soap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        MainTest.ServiceReferenceDMP.HelloWorldResponse HelloWorld(MainTest.ServiceReferenceDMP.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<MainTest.ServiceReferenceDMP.HelloWorldResponse> HelloWorldAsync(MainTest.ServiceReferenceDMP.HelloWorldRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 str 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Print", ReplyAction="*")]
        MainTest.ServiceReferenceDMP.PrintResponse Print(MainTest.ServiceReferenceDMP.PrintRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Print", ReplyAction="*")]
        System.Threading.Tasks.Task<MainTest.ServiceReferenceDMP.PrintResponse> PrintAsync(MainTest.ServiceReferenceDMP.PrintRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 xmlData 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DMPProtocol", ReplyAction="*")]
        MainTest.ServiceReferenceDMP.DMPProtocolResponse DMPProtocol(MainTest.ServiceReferenceDMP.DMPProtocolRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DMPProtocol", ReplyAction="*")]
        System.Threading.Tasks.Task<MainTest.ServiceReferenceDMP.DMPProtocolResponse> DMPProtocolAsync(MainTest.ServiceReferenceDMP.DMPProtocolRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 str 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DbTest", ReplyAction="*")]
        MainTest.ServiceReferenceDMP.DbTestResponse DbTest(MainTest.ServiceReferenceDMP.DbTestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DbTest", ReplyAction="*")]
        System.Threading.Tasks.Task<MainTest.ServiceReferenceDMP.DbTestResponse> DbTestAsync(MainTest.ServiceReferenceDMP.DbTestRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public MainTest.ServiceReferenceDMP.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(MainTest.ServiceReferenceDMP.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public MainTest.ServiceReferenceDMP.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(MainTest.ServiceReferenceDMP.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PrintRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Print", Namespace="http://tempuri.org/", Order=0)]
        public MainTest.ServiceReferenceDMP.PrintRequestBody Body;
        
        public PrintRequest() {
        }
        
        public PrintRequest(MainTest.ServiceReferenceDMP.PrintRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PrintRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string str;
        
        public PrintRequestBody() {
        }
        
        public PrintRequestBody(string str) {
            this.str = str;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PrintResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PrintResponse", Namespace="http://tempuri.org/", Order=0)]
        public MainTest.ServiceReferenceDMP.PrintResponseBody Body;
        
        public PrintResponse() {
        }
        
        public PrintResponse(MainTest.ServiceReferenceDMP.PrintResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PrintResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PrintResult;
        
        public PrintResponseBody() {
        }
        
        public PrintResponseBody(string PrintResult) {
            this.PrintResult = PrintResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DMPProtocolRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DMPProtocol", Namespace="http://tempuri.org/", Order=0)]
        public MainTest.ServiceReferenceDMP.DMPProtocolRequestBody Body;
        
        public DMPProtocolRequest() {
        }
        
        public DMPProtocolRequest(MainTest.ServiceReferenceDMP.DMPProtocolRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DMPProtocolRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xmlData;
        
        public DMPProtocolRequestBody() {
        }
        
        public DMPProtocolRequestBody(string xmlData) {
            this.xmlData = xmlData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DMPProtocolResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DMPProtocolResponse", Namespace="http://tempuri.org/", Order=0)]
        public MainTest.ServiceReferenceDMP.DMPProtocolResponseBody Body;
        
        public DMPProtocolResponse() {
        }
        
        public DMPProtocolResponse(MainTest.ServiceReferenceDMP.DMPProtocolResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DMPProtocolResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int DMPProtocolResult;
        
        public DMPProtocolResponseBody() {
        }
        
        public DMPProtocolResponseBody(int DMPProtocolResult) {
            this.DMPProtocolResult = DMPProtocolResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DbTestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DbTest", Namespace="http://tempuri.org/", Order=0)]
        public MainTest.ServiceReferenceDMP.DbTestRequestBody Body;
        
        public DbTestRequest() {
        }
        
        public DbTestRequest(MainTest.ServiceReferenceDMP.DbTestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DbTestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string str;
        
        public DbTestRequestBody() {
        }
        
        public DbTestRequestBody(string str) {
            this.str = str;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DbTestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DbTestResponse", Namespace="http://tempuri.org/", Order=0)]
        public MainTest.ServiceReferenceDMP.DbTestResponseBody Body;
        
        public DbTestResponse() {
        }
        
        public DbTestResponse(MainTest.ServiceReferenceDMP.DbTestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DbTestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int DbTestResult;
        
        public DbTestResponseBody() {
        }
        
        public DbTestResponseBody(int DbTestResult) {
            this.DbTestResult = DbTestResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService2019SoapChannel : MainTest.ServiceReferenceDMP.WebService2019Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService2019SoapClient : System.ServiceModel.ClientBase<MainTest.ServiceReferenceDMP.WebService2019Soap>, MainTest.ServiceReferenceDMP.WebService2019Soap {
        
        public WebService2019SoapClient() {
        }
        
        public WebService2019SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService2019SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService2019SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService2019SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MainTest.ServiceReferenceDMP.HelloWorldResponse MainTest.ServiceReferenceDMP.WebService2019Soap.HelloWorld(MainTest.ServiceReferenceDMP.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            MainTest.ServiceReferenceDMP.HelloWorldRequest inValue = new MainTest.ServiceReferenceDMP.HelloWorldRequest();
            inValue.Body = new MainTest.ServiceReferenceDMP.HelloWorldRequestBody();
            MainTest.ServiceReferenceDMP.HelloWorldResponse retVal = ((MainTest.ServiceReferenceDMP.WebService2019Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MainTest.ServiceReferenceDMP.HelloWorldResponse> MainTest.ServiceReferenceDMP.WebService2019Soap.HelloWorldAsync(MainTest.ServiceReferenceDMP.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<MainTest.ServiceReferenceDMP.HelloWorldResponse> HelloWorldAsync() {
            MainTest.ServiceReferenceDMP.HelloWorldRequest inValue = new MainTest.ServiceReferenceDMP.HelloWorldRequest();
            inValue.Body = new MainTest.ServiceReferenceDMP.HelloWorldRequestBody();
            return ((MainTest.ServiceReferenceDMP.WebService2019Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MainTest.ServiceReferenceDMP.PrintResponse MainTest.ServiceReferenceDMP.WebService2019Soap.Print(MainTest.ServiceReferenceDMP.PrintRequest request) {
            return base.Channel.Print(request);
        }
        
        public string Print(string str) {
            MainTest.ServiceReferenceDMP.PrintRequest inValue = new MainTest.ServiceReferenceDMP.PrintRequest();
            inValue.Body = new MainTest.ServiceReferenceDMP.PrintRequestBody();
            inValue.Body.str = str;
            MainTest.ServiceReferenceDMP.PrintResponse retVal = ((MainTest.ServiceReferenceDMP.WebService2019Soap)(this)).Print(inValue);
            return retVal.Body.PrintResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MainTest.ServiceReferenceDMP.PrintResponse> MainTest.ServiceReferenceDMP.WebService2019Soap.PrintAsync(MainTest.ServiceReferenceDMP.PrintRequest request) {
            return base.Channel.PrintAsync(request);
        }
        
        public System.Threading.Tasks.Task<MainTest.ServiceReferenceDMP.PrintResponse> PrintAsync(string str) {
            MainTest.ServiceReferenceDMP.PrintRequest inValue = new MainTest.ServiceReferenceDMP.PrintRequest();
            inValue.Body = new MainTest.ServiceReferenceDMP.PrintRequestBody();
            inValue.Body.str = str;
            return ((MainTest.ServiceReferenceDMP.WebService2019Soap)(this)).PrintAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MainTest.ServiceReferenceDMP.DMPProtocolResponse MainTest.ServiceReferenceDMP.WebService2019Soap.DMPProtocol(MainTest.ServiceReferenceDMP.DMPProtocolRequest request) {
            return base.Channel.DMPProtocol(request);
        }
        
        public int DMPProtocol(string xmlData) {
            MainTest.ServiceReferenceDMP.DMPProtocolRequest inValue = new MainTest.ServiceReferenceDMP.DMPProtocolRequest();
            inValue.Body = new MainTest.ServiceReferenceDMP.DMPProtocolRequestBody();
            inValue.Body.xmlData = xmlData;
            MainTest.ServiceReferenceDMP.DMPProtocolResponse retVal = ((MainTest.ServiceReferenceDMP.WebService2019Soap)(this)).DMPProtocol(inValue);
            return retVal.Body.DMPProtocolResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MainTest.ServiceReferenceDMP.DMPProtocolResponse> MainTest.ServiceReferenceDMP.WebService2019Soap.DMPProtocolAsync(MainTest.ServiceReferenceDMP.DMPProtocolRequest request) {
            return base.Channel.DMPProtocolAsync(request);
        }
        
        public System.Threading.Tasks.Task<MainTest.ServiceReferenceDMP.DMPProtocolResponse> DMPProtocolAsync(string xmlData) {
            MainTest.ServiceReferenceDMP.DMPProtocolRequest inValue = new MainTest.ServiceReferenceDMP.DMPProtocolRequest();
            inValue.Body = new MainTest.ServiceReferenceDMP.DMPProtocolRequestBody();
            inValue.Body.xmlData = xmlData;
            return ((MainTest.ServiceReferenceDMP.WebService2019Soap)(this)).DMPProtocolAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MainTest.ServiceReferenceDMP.DbTestResponse MainTest.ServiceReferenceDMP.WebService2019Soap.DbTest(MainTest.ServiceReferenceDMP.DbTestRequest request) {
            return base.Channel.DbTest(request);
        }
        
        public int DbTest(string str) {
            MainTest.ServiceReferenceDMP.DbTestRequest inValue = new MainTest.ServiceReferenceDMP.DbTestRequest();
            inValue.Body = new MainTest.ServiceReferenceDMP.DbTestRequestBody();
            inValue.Body.str = str;
            MainTest.ServiceReferenceDMP.DbTestResponse retVal = ((MainTest.ServiceReferenceDMP.WebService2019Soap)(this)).DbTest(inValue);
            return retVal.Body.DbTestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MainTest.ServiceReferenceDMP.DbTestResponse> MainTest.ServiceReferenceDMP.WebService2019Soap.DbTestAsync(MainTest.ServiceReferenceDMP.DbTestRequest request) {
            return base.Channel.DbTestAsync(request);
        }
        
        public System.Threading.Tasks.Task<MainTest.ServiceReferenceDMP.DbTestResponse> DbTestAsync(string str) {
            MainTest.ServiceReferenceDMP.DbTestRequest inValue = new MainTest.ServiceReferenceDMP.DbTestRequest();
            inValue.Body = new MainTest.ServiceReferenceDMP.DbTestRequestBody();
            inValue.Body.str = str;
            return ((MainTest.ServiceReferenceDMP.WebService2019Soap)(this)).DbTestAsync(inValue);
        }
    }
}
